### ISSUE TITLE
After flashing the RTOS_A36plus_MAX firmware, how to flash the original firmware?

### ISSUE THREAD

**Issue by brainavat** [Jamie793/A36Plus_Radio#6]
![b868f171d5bc9352c3f2749faa1e730](https://github.com/user-attachments/assets/d058eac0-3e78-4cbd-9ee7-088dcd85c18c)

**Comment by Tunas1337** [comment]
Hi, you can power on the radio with both of the side buttons pressed. You will see a white screen. Then, flash the firmware back as normal.

**Comment by brainavat** [comment]
![下载](https://github.com/user-attachments/assets/03018e3a-e9c6-4918-80af-bb3b234a5024)
